const jobSkills = [
    'JavaScript',
    'JavaScript',
    'React.js',
    'Node.js',
    'HTML5',
    'CSS3',
    'Python',
    'Java',
    'C#',
    'Angular',
    'Vue.js',
    'SQL',
    'MongoDB',
    'Git',
    'Redux',
    'RESTful API',
    'Responsive Design',
    'Agile Development',
    'Problem Solving',
    'Real-Time Analytics',
    'Software Testing',
    'Selenium',
    'JUnit',
    'TestNG',
    'Postman',
    'Appium',
    'QA',
    'Manual Testing',
    'Functional Testing',
    'Integration Testing',
    'Performance Testing',
    'Security Testing',
    'Test Strategy',
    'Test Planning',
    'Test Management',
    'QA Process',
    'Test Case',
    'Test Suite',
    'Test Execution',
    'Test Analysis',
    'Test Reporting',
    'Bug Reporting',
    'Defect Tracking',
    'Data Mining',
    'Big Data',
    'Apache Spark',
    'Hadoop',
    'TensorFlow',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'Tableau',
    'Power BI',
    'Business Intelligence',
    'Data Visualization',
    'ETL',
    'EDA',
    'MLOps',
    'DVC',
    'Hydra',
    'Gradio',
    'Rasa',
    'NLTK',
    'TorchText',
    'CVAT',
    'Weights & Biases',
    'Flask',
    'FastAPI',
    'Django Rest Framework',
    'Electron',
    'Electric Imp',
    'Piccolo',
    'GObject',
    'Kivy',
    'Rhino',
    'JVM',
    'WebRTC',
    'ORTC',
  ];

  export default jobSkills;